### ISSUE TITLE
Get incorrect solid of IfcSweptDiskSolid

### ISSUE THREAD

**Issue by luciferz2012** [xBimTeam/XbimGeometry#25] opened 2016-09-04 10:20 UTC
I got a rebar.ifc as attached below but couldn't show reinforcingbars/meshes correctly in xBim, showing only small disks at starting points.

I tried to get a solid of IfcSweptDiskSolid (#2866 in the attached ifc file, with R=6.35, L=3500), and inspect its three faces, which areas are 39.90, 126.68, 126.68.

Since 126.68 = 6.35 x 6.35 x 3.14, the last two faces are up and down faces. And the 39.90 should be the lateral area.

39.90 = 6.35 x 2 x 3.14 = R x 2 x PI x L, so the actual length "L" of the solid is 1 instead of 3500.

**Conclusion**: when generating solid of IfcSweptDiskSolid, the length parameter is incorrectly set.

I guess it is incorrectly set to the endparam of IfcSweptDiskSolid, which is 1.0 and means that solid is swept to the end of the directrix.

[rebar.ifc.txt](https://github.com/xBimTeam/XbimGeometry/files/453869/rebar.ifc.txt)

ReinforcingMesh in xBim (wrong)
![rebar](https://cloud.githubusercontent.com/assets/2638998/18230285/c06116ea-72c8-11e6-90c2-bddc853674fe.png)

ReinforcingMesh in IfcViewer (right)
![_20160904181911](https://cloud.githubusercontent.com/assets/2638998/18230394/177dc452-72cc-11e6-87aa-efe8341d6a20.png)

**Comment by martin1cerny** [comment] 2016-09-24 10:41
We are on the case now and we just solved it. There is not a clear agreement about how parametrization of directrix should work. Revit does this in a way which is generally regarded less suitable. We will publish it to develop branch today.

**Comment by luciferz2012** [comment] 2016-09-26 00:36
Thank you for your work!

**Comment by SteveLockley** [comment] 2016-09-28 14:36
This is confirmed fixed now in the develop branch. The problem is with the trimming of directrix for swept disks, the tool that exported this file id defining the trim as a number between 0 and 1. Most tools give an explicit distance along the line of the directrix, i.e. for the 0 and 1 case this is the entire length of the directrix and would be specified as 0 .. Length(directirx). We have put a work around to support this problem and the output is as you show above now.

**Closed by SteveLockley** 2016-09-28 14:36 UTC
