### ISSUE TITLE
Wrong geometry processing with IfcBooleanClippingResult

### ISSUE THREAD

**Issue by guenter1holzeder** [xBimTeam/XbimGeometry#158] opened 2019-01-29 08:16 UTC
The result differs from any other IFC Viewer. 

![image](https://user-images.githubusercontent.com/42930849/51893630-c13bab80-23a5-11e9-8318-948da8a74133.png)

![image](https://user-images.githubusercontent.com/42930849/51893638-c8fb5000-23a5-11e9-9ee6-39af9a035bdd.png)

[IfcWallStandardCase IfcBooleanClippingResult.zip](https://github.com/xBimTeam/XbimGeometry/files/2806592/IfcWallStandardCase.IfcBooleanClippingResult.zip)

**Comment by chingham** [comment] 2019-02-12 10:54
I have the same problem with the exact same model (rac_basic_sample_project from Revit)
Any update on this so far ?

**Comment by guenter1holzeder** [comment] 2019-02-15 15:22
I found another sample with same issue

![image](https://user-images.githubusercontent.com/42930849/52865776-a6a35980-313d-11e9-915b-4bdd5369b8a4.png)

![image](https://user-images.githubusercontent.com/42930849/52865796-b28f1b80-313d-11e9-9313-918b16145d70.png)
(Solibri)

[IfcWallStandardCase invalid body.zip](https://github.com/xBimTeam/XbimGeometry/files/2869768/IfcWallStandardCase.invalid.body.zip)

**Comment by martin1cerny** [comment] 2019-02-15 15:25
Thanks, we will investigate. Any insights @SteveLockley?

**Comment by bekraft** [comment] 2019-02-20 14:13
The root cause here was some weird code concerning the step of converting a clipping result to a XbimSolidSet. The second operand of the root clipping entity has never been investigated. Should work now.
![158](https://user-images.githubusercontent.com/10463824/53097538-0032cc00-3522-11e9-90e0-e9e52a8ed305.png)

**Comment by andyward** [comment] 2019-03-27 11:40
Initial clipping issue fixed in PR #162 . Now in develop

2nd Issue also fixed

**Closed by andyward** 2019-03-27 11:40 UTC
Labels: bug
