### ISSUE TITLE
Failed to load Xbim.Geometry.Engine64.dll

### ISSUE THREAD

**Issue by GVladislavG** [xBimTeam/XbimGeometry#312] opened 2021-02-11 13:19 UTC
Some of my colleagues can't run my xBim Application with this log:

Failed to load Xbim.Geometry.Engine64.dll
в Xbim.Geometry.Engine.Interop.XbimGeometryEngine..ctor(ILogger`1 logger)
   в Xbim.ModelGeometry.Scene.Xbim3DModelContext.get_Engine()
   в Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs)

But some of them have no problem and everything works well. 
What's the reason of this truble?

I put these files to application folder:
![Files](https://user-images.githubusercontent.com/77204365/107641679-f2cdf980-6c84-11eb-9029-c5f44c186d8e.png)

**Comment by martin1cerny** [comment] 2021-02-11 16:29
You need to check your deployment routines.

**Comment by GVladislavG** [comment] 2021-02-11 18:09
And what deployment routines do I need? I just give them this files. 
There's no any installer or deployment process for my xBim application.

**Comment by martin1cerny** [comment] 2021-02-12 09:30
They probably don't have the right version of  Microsoft Visual C++ Redistributable package in their system. This usually comes with updates, but you are better to check.

**Comment by andyward** [comment] 2021-02-12 13:07
This is usually one of a several issues, all of which have solutions in the Issues in this repo:

1. Missing VC runtime that the Geometry Engine depends on. Installing the latest Windows 10 SDK should do the trick, or else see https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
2. Using incompatible dependencies. e.g. a v5 Geometry with a v4 Essentials, or vice versa - we broke some interfaces between versions
3. Bringing in an incompatible version of Microsoft.Extensions.Logging transitively from some 3rd party dependency.  i.e. we use M.E.L 2.1.1 but that's not compatible with 1.x versions (e.g. older Revit has this issue)
4. The native geometry engine is not being copied into bin, or it's the wrong platform. E.g. 32 bit apps should have Xbim.Geometry.Engine32.dll while 64bit apps should have Xbim.Geometry.Engine64.dll. If you build for MSIL what you deploy depends on if your OS is 32 bit or 64bit...
5. ASP.NET (Core) Web apps have issues when both 64bit and 32 bit Geometry Engines are present in the bin folder resulting in a BadImageFormatException

In your case it looks like one of 1-4 might be the issue. Hard to tell without the exception.

**Comment by theextremeandy** [comment] 2021-03-19 10:02
Hi
i encountered the same error
my versions are:
Essentials 5.1.323
Geometry 5.1.403
through analyzing the debug output I found that the Engine64.dll file was taken from the GAC
deleted the GAC everything works correctly

hope it helps

**Comment by andyward** [comment] 2021-03-19 12:25
That's a good call. It's pretty hard to justify using the GAC these days.

**Comment by prasuncct** [comment] 2021-05-07 11:30
I found that this issue was caused by windows feature- auto blocking the dlls and exes downloaded from network. I ticked the unblock checkbox in properties of Xbim.Geometry.Engine64.dll and it worked. This unblock feature or bug seems to block only references of references as this dll is referenced by Xbim.Geometry.Engine.Interop.dll .
![image](https://user-images.githubusercontent.com/82934147/117442854-485b2f00-af72-11eb-90fa-d60bdf9d6e35.png)

**Comment by Woudjee** [comment] 2024-03-27 15:15
I have the exact same problem. I made an empty .NET Core 8.0 project (and also tried the same code in .NET Framework 4.7.2). In both cases, it is not able to create a context using the code below:
![image](https://github.com/xBimTeam/XbimGeometry/assets/84737524/9b197f15-1a64-4c23-bb55-30af8912f00d)

When trying to create the context, the following error is thrown: System.IO.FileLoadException: 'Failed to load Xbim.Geometry.Engine64.dll'

When looking in the bin folder, you can clearly see that the dll is there:
![image](https://github.com/xBimTeam/XbimGeometry/assets/84737524/c0fdde95-b0ae-4d2d-91f4-7629c6007523)

The following versions are installed:
![image](https://github.com/xBimTeam/XbimGeometry/assets/84737524/3a57737b-612e-4ff3-bbe3-bf97af71103f)

It is still unclear to me how to resolve the issue. Any more ideas?

**Comment by Woudjee** [comment] 2024-03-27 15:34
> This is usually one of a several issues, all of which have solutions in the Issues in this repo:
> 
> 1. Missing VC runtime that the Geometry Engine depends on. Installing the latest Windows 10 SDK should do the trick, or else see https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
> 2. Using incompatible dependencies. e.g. a v5 Geometry with a v4 Essentials, or vice versa - we broke some interfaces between versions
> 3. Bringing in an incompatible version of Microsoft.Extensions.Logging transitively from some 3rd party dependency.  i.e. we use M.E.L 2.1.1 but that's not compatible with 1.x versions (e.g. older Revit has this issue)
> 4. The native geometry engine is not being copied into bin, or it's the wrong platform. E.g. 32 bit apps should have Xbim.Geometry.Engine32.dll while 64bit apps should have Xbim.Geometry.Engine64.dll. If you build for MSIL what you deploy depends on if your OS is 32 bit or 64bit...
> 5. ASP.NET (Core) Web apps have issues when both 64bit and 32 bit Geometry Engines are present in the bin folder resulting in a BadImageFormatException
> 
> In your case it looks like one of 1-4 might be the issue. Hard to tell without the exception.

In reply to your suggestions:
1. I downloaded the latest version and restarted my computer, but it did not change anything.
2. As can be seen in my previous reply, I was using version 6.xxx for XBim.Essentials. I just downgraded to 5.xxxx. This also did not solve the problem.
3. 3. I am not using loggin as it is still an empty project with essentially only the two lines of code from my previous message.
4. It IS being copied.
5. It is a class library and the 'entry point' for reaching it is currently a unit test project. Might this be the issue? (Will try it out right after I post this message).

And about the GAC thing. I don't know how to do this. Cannot find any clear information online, but I might be looking at the wrong place.

**Comment by Woudjee** [comment] 2024-03-27 16:06
Update: I looked into the GAC situation. The dll's are not present there, so that is also not my problem. I am sincerely out of inspiration now. Thank you for any help you can give me.

**Comment by Woudjee** [comment] 2024-03-27 16:48
So, I created a new solution and copied and pasted the few lines of code that I had, reinstated the identical references to the NuGet packages and it worked.

So this brings me (most likely) to point 3, logging. The solution where my initial project was added to consists of 30 projects. One of them is using logging. I suppose this is the problem. I haven't figured this out yet, but it seems like a logical lead.

I will post here again when I figure it out.

**Comment by andyward** [comment] 2024-03-27 18:31
Thanks for the update @Woudjee - glad you've at least started to track it down. If you're able to identify the version of M.E.Logging that you use you should be able to reproduce in your clean solution, which might give us something to go at.
Rightly or Wrongly, under .net8 we depend on ME.Logging.Abstractions 8.0.0.

See https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Common/Xbim.Common.csproj

If you created a library targeting .netstandard2.x it would use a 2.1.1 or newer.

**Comment by Woudjee** [comment] 2024-03-27 19:53
I checked out the file you shared and I experimented in the context of my main (30 project) solution and my new isolated solution.

In my main solution, I removed all project references. My structure there was therefore as follow (.NET 8.0):
- IFC project -> IFC.Test project

This meant that the logging going on in the solution was fully outside the scope the IFC project. Besides this, I also tried to remove logging or using an older version, but this is too deeply integrated into our project and therefore not appropriate to remove for a POC. Anyhow, it still does not work!

I also tried adding logging to my new solution and applying this to a similar project(s)-setup as in my main solution. Here, it works.

I therefore gently conclude that logging is not the culprit here. Any suggestions what I can do to further isolate it? Please note that the IFC project in my main solution has no references to any project inside this solution and is therefore not bothered by logging. The only thing interesting in my main solution is that Any CPU, x64 and x86 is all allowed/specified. Could this have any influence?

**Comment by Woudjee** [comment] 2024-03-27 20:03
Okay I figured it out. It simply won't work when using a unit test as an entry point. This is annoying, because this will make developing and testing my code significantly more challenging. If you want, I can share a repo so you can reproduce the issue. But it is as follows:

- Class lib project (with the two lines of code I shared in a method + obviously calling `IfcStore.Open(file)`)
- A test project (which I use to call the method in the class lib).

You will see that it doesn't work.

Then, when doing exactly the same with with a console application, it works. Why could it be that I am not able to do this when the caller is a test method?

**Comment by andyward** [comment] 2024-03-27 20:06
If you can share a repo that would be great!

**Comment by Woudjee** [comment] 2024-03-27 20:07
I will make it straight away. Give me a few mins!

**Comment by Woudjee** [comment] 2024-03-27 20:22
Okay the problem was yet something else. On the one hand it makes sense, on the other I'm still a bit confused. While I was preparing a tidy solution for you, I did the following:

![image](https://github.com/xBimTeam/XbimGeometry/assets/84737524/82e4643f-82b7-4f4b-8a6b-ba9a9eb6b9db)

The screenshot above is how I always approach my project references (only referencing nugets or any other references where necessary). I hereby rely on the fact that the lowest project (ClassLib) has the appropriate references and that the calling project can work with the respective models. This has always worked for me.

When doing it exactly as in the screenshot above, neither the console application nor the test project worked. I then realized a slight difference to the project I got working. I therefore changed the Xbim references to:

![image](https://github.com/xBimTeam/XbimGeometry/assets/84737524/dd8d6bf4-9857-442d-ba5d-8e748334dadb)

I'm glad to inform you that (as expected) both projects work and are able to create the context.

__________________

Can you explain to me why this problem occured? I can kind of visualize in my head what might be the root cause here (namely that the GeometryXX.dll is not being copied to the bin folder of the calling project) but at the same time, I expected that this would be handled.

__________________

**@ people looking for my solution: ensure you have referenced all Xbim nugets in your calling project, not solely in the project where you use it.**

**Comment by andyward** [comment] 2024-03-27 21:46
OK. Sounds like #380 - which is fixed in the upcoming v6 release. Thansk for all the effort digging into this.

**Comment by Woudjee** [comment] 2024-04-03 06:22
Thank you Andy, sounds good. I will keep an eye out on the new version :)

**Closed** 2024-04-04 11:15 UTC
Labels: awaiting closure

**Comment by Rachvel** [comment] 2024-08-27 13:57
I've found another solution how to force copy appropriate Xbim.Geometry.EngineXX.dll into output folder. It uses NuGet package **GeneratePathProperty**, see [StackOverflow](https://stackoverflow.com/questions/77110180/visual-studio-variable-for-nuget-root-path).

Our project is MultiTargetFrameworks WPF application and Xbim NuGets are linked to one .dll. The above mentioned solution to add Xbim NuGet package reference in calling project doesn't work in our case. Used TargetFramework is net8.0-windows.

Following lines in dll's .csproj ensures expected behavior:

```
<ItemGroup>
	<PackageReference Include="Xbim.Geometry.Engine.Interop" Version="5.1.437" GeneratePathProperty="True" />
</ItemGroup>
```
Property **GeneratePathProperty** set on true generates NuGet package variable PkgXbim_Geometry_Engine_Interop, which you can use as path reference in another place in .csproj. 

For x64 you can use:
```
<ItemGroup Condition="'$(Platform)' == 'x64'">
	<Content Include="$(PkgXbim_Geometry_Engine_Interop)\build\net472\Xbim.Geometry.Engine64.dll" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>
```
And for Win32:
```
<ItemGroup Condition="'$(Platform)' == 'Win32'">
	<Content Include="$(PkgXbim_Geometry_Engine_Interop)\build\net472\Xbim.Geometry.Engine32.dll" CopyToOutputDirectory="PreserveNewest"/>
</ItemGroup>
```
You can combine conditions according your needs.
This solution requires only one NuGet package reference Xbim.Geometry.Engine.Interop in calling project, if you have others xBim NuGet's references somewhere else.

**Comment by andyward** [comment] 2024-08-27 15:29
Thanks for sharing this. That's a useful workaround until the transitive nuget deployment in the netcore6 branch is merged.

**Comment by Rachvel** [comment] 2024-08-27 15:36
This can be added exactly in NuGet's package .target file, see [SO](https://stackoverflow.com/questions/28851338/why-the-condition-attribute-doesnt-work-for-the-itemgroup-element).
Maybe now condition doesn't work properly. Without it works. But I'll make it work ;-).

**Comment by Rachvel** [comment] 2024-08-28 14:26
@andyward I did some testing with interop nuget.
Just add these lines in nuget's .target file:
```
  <ItemGroup Condition="'$(Platform)' == 'x64'">
      <None Include="$(MSBuildThisFileDirectory)\Xbim.Geometry.Engine64.dll">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
  </ItemGroup>
  <ItemGroup Condition="'$(Platform)' == 'x86'">
      <None Include="$(MSBuildThisFileDirectory)\Xbim.Geometry.Engine32.dll">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
  </ItemGroup>
```
and Xbim.Geometry.EngineXX.dll will automatically copy in output folder. See file 
[Xbim.Geometry.Engine.Interop.zip](https://github.com/user-attachments/files/16784786/Xbim.Geometry.Engine.Interop.zip)
It works in our project.
