### ISSUE TITLE
Bug in XbimWire with IFC2x3 file

### ISSUE THREAD

**Issue by johnnyontheweb** [xBimTeam/XbimGeometry#132] opened 2018-10-26 17:19 UTC
#### Expected behavior:
see a beam structure when loading IFC, see related in https://github.com/xBimTeam/XbimWindowsUI/issues/94

#### Actual behavior or exception details:
Xbim.Geometry.XbimGeometryCreator EE001: Failed to create geometry #33 of type IfcExtrudedAreaSolid, General Error Creating IfcExtrudedAreaSolid, #33

#### Versions of xBIM Packages:

- xBIM Essentials: 4
- xBIM Geometry: 4

#### Minimal code (or steps) to reproduce the issue:
the exception (not managed) is given into XbimConvert.cpp:
`TopLoc_Location XbimConvert::ToLocation(IIfcAxis2Placement2D^ axis2D)`
at the first line:
`gp_Pnt2d loc(axis2D->Location->X, axis2D->Location->Y);`
it seems that axis2D, if IFC2x3 is used, does not have any Location prop.

#### Minimal file to reproduce the issue:
[wex.zip](https://github.com/xBimTeam/XbimGeometry/files/2520145/wex.zip)

**Comment by jomijomi** [comment] 2018-11-01 20:07
Hi,
looking at the file I think that the problem is at entity 30: 
#30=IFCAXIS2PLACEMENT2D($,$); 
According to the IFC spec. the first argument is NOT optional. If you just change that line to:
#30=IFCAXIS2PLACEMENT2D(#21,$);
I think it will import correctly. 
So, in other words, the file is not a fully valid IFC-file. I assume that other viewers just add a (0,0) coordinate as the first argument (similar to what I did) if it is omitted.
/Mikael

**Comment by johnnyontheweb** [comment] 2018-11-02 10:06
Thanks for the reply. I think that a warning should be placed somewhere in xbim essentials, since one could believe that the generated file is correct if other viewers are used.

**Comment by SteveLockley** [comment] 2018-11-09 12:20
This is now fixed in the forthcoming V5 and will default to 0,0 where no location is given. The Xbim schema validation tools can be used by developers to avoid creating ifc files that are invalid, but I felt it was unnecessary to bother users with this problem as they will expect behaviour to be the same as other Ifc Toolkits

**Closed by SteveLockley** 2018-11-09 12:20 UTC
Labels: bug
