### ISSUE TITLE
Wexbim file size increased compared to original IFC file

### ISSUE THREAD

**Issue by ravigarg1** [xBimTeam/XbimGeometry#41] opened 2017-03-09 11:30 UTC
Hello,

I was wondering if anyone has a clue why the converted wexbim file size is > then the IFC file. What could be possible reason and what can we do to reduce the size because such a large size means it will not display in the webUI.

Thanks.

**Comment by CBenghi** [comment] 2017-04-21 16:27
Duplicate of https://github.com/xBimTeam/XbimGeometry/issues/49
Closing

**Closed by CBenghi** 2017-04-21 16:27 UTC
