### ISSUE TITLE
EE001: Failed to create geometry #362098 of type IfcAdvancedBrep, General Error Creating IfcAdvancedBrep

### ISSUE THREAD

**Issue by Belrius** [xBimTeam/XbimGeometry#134] opened 2018-11-07 02:30 UTC
#### Expected behavior:

Apologies if this is just not implement as yet, or is covered elsewhere. I'm a bit new and am not sure if there are other sources of info as yet. 

I'm having problems loading an IFC4  IfC file, presumably because it contains an IfcTrimmedCurve where all of the other models I've successfully loaded do not?

Can you let me know what direction I should be going in with this? 

Many thanks

*Screenshot or image of desired state:*

#### Actual behavior or exception details:

Error in my program,
![image](https://user-images.githubusercontent.com/1472309/48106627-eb3e6f80-e287-11e8-8479-de54f8a4cf38.png)

Error in XBim Explorer, however XBim Explorer still loads the model.
![image](https://user-images.githubusercontent.com/1472309/48106410-0e1c5400-e287-11e8-9056-4d80e0883fba.png)
*Screenshot or image of desired state:*

#### Versions of xBIM Packages:

- xBIM Essentials: 4.0.29
- xBIM Geometry: 4.0.11

#### Minimal code (or steps) to reproduce the issue:
```cs
using (var model = IfcStore.Open(file.ifc))
{
    ...
}
```

#### Minimal file to reproduce the issue:
*(IFC files need to be zipped to be uploaded. Than just drag & drop here)*
[werribee.zip](https://github.com/xBimTeam/XbimGeometry/files/2555803/werribee.zip)

**Comment by martin1cerny** [comment] 2018-11-07 07:53
Hi @Belrius, I just checked and it seems that Revit Exporter starts to create some new geometry forms we haven't encounter yet. We will look at these.

**Comment by SteveLockley** [comment] 2018-11-09 11:31
Hi  @Belrius, thanks for finding this.  This is now fixed and trimmed curves made of trimmed curves are now implemented as part of advanced breps.
We are currently publishing a major release V5 with many fixes. This will be in that release.

**Closed by SteveLockley** 2018-11-09 11:31 UTC
Labels: bug, investigating

**Comment by jFontoura** [comment] 2020-09-29 20:30
hello, I'm getting this same error when opening a certain ifc file in xplorer, it still opens the model, but if I try to convert it from ifc to wexbim there is an error and the file is not generated.

**exception thrown by the compiler:**
Xbim.Common.Exceptions.XbimException: 'Processing halted due to model error'

**follow the version of my packages, I used the latest version available in nuget**
  package id="Xbim.Common" version="5.1.297" targetFramework="net472" 
  package id="Xbim.Essentials" version="5.1.297" targetFramework="net472" 
  package id="Xbim.Geometry.Engine.Interop" version="5.1.328" targetFramework="net472" 
  package id="Xbim.Ifc" version="5.1.297" targetFramework="net472" 
  package id="Xbim.Ifc2x3" version="5.1.297" targetFramework="net472" 
  package id="Xbim.Ifc4" version="5.1.297" targetFramework="net472"
  package id="Xbim.IO.Esent" version="5.1.297" targetFramework="net472" 
  package id="Xbim.IO.MemoryModel" version="5.1.297" targetFramework="net472" 
  package id="Xbim.ModelGeometry.Scene" version="5.1.328" targetFramework="net472" 
  package id="Xbim.Tessellator" version="5.1.297" targetFramework="net472"

**Comment by andyward** [comment] 2020-09-30 08:10
Can you share any warnings or errors in Xplorer? And the full exception from the wexbim output

It seems unlikely it's the same issue if the model displays in Xplorer but won't convert to wexbim. When you save as wexbim it's just serialising the computed mesh - but I guess it could be a side effect of a geometry failure.

**Comment by jFontoura** [comment] 2020-09-30 12:28
really, i don't believe it is the same problem anymore, since the xplorer i tested is still in version 4, this problem in my program occurs in version 5, should i open a new issue?

![image](https://user-images.githubusercontent.com/58859317/94684053-de084f00-02fd-11eb-826c-9283055e9581.png)

**the image below shows the error displayed by the compiler, below the image I pasted the details**

![image](https://user-images.githubusercontent.com/58859317/94683506-0a6f9b80-02fd-11eb-8792-2400c77d4234.png)

Xbim.Common.Exceptions.XbimException
  HResult = 0x80131500
  Message = Processing halted due to model error
  Source = Xbim.ModelGeometry.Scene
  StackTrace:
   in Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteShapeGeometries (XbimCreateContextHelper contextHelper, ReportProgressDelegate progDelegate, IGeometryStoreInitialiser geometryStore, XbimGeometryType geomStorageType)
   in Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext (ReportProgressDelegate progDelegate, Boolean adjustWcs)
   in convertIfcToWexbim.Program.Main (String [] args) in C: \ Users \ const \ Documents \ code \ c # \ convertIfcToWexbim \ convertIfcToWexbim \ Program.cs: line 22

  This exception was originally generated in this call stack:
    [External Code]

Internal exception 1:
AggregateException: One or more errors.

Internal exception 2:
NullReferenceException: Object reference not defined for an instance of an object.

**Comment by martin1cerny** [comment] 2020-10-01 06:40
It might be better to open a new issue as the original issue was resolved. A lot of work has gone into Advanced B-Rep processing lately and it is possible that we handle more than we did previously, Or, despite the fact we have a test suite and regression testing,  there might be a regression. Can you share the IFC file? If not entire file, you can use xbim to extract just a single product with the failing geometry and provide us with that (that is actualy the prefered option anyway).
