### ISSUE TITLE
Could not load file or assembly 'Xbim.Geometry.Engine64' or one of its dependencies. An attempt was made to load a program with an incorrect format.

### ISSUE THREAD

**Issue by Nandhakumar2187** [xBimTeam/XbimGeometry#218] opened 2019-09-17 07:40 UTC
Hi,
We have tried to convert the IFC file to Wexbim. we have received the below error.

**Could not load file or assembly 'Xbim.Geometry.Engine64' or one of its dependencies. An attempt was made to load a program with an incorrect format.** 

1. We have created the new project in Visual Studio 2017.
2. We have downloaded the below dlls from nuget package.
          - Xbim.Ifc related dlls (version 5.1.0.0)
          - Xbim.Geometry related DLLS (version 5.1.0.0)

3. We have used .Net framework 4.7.1.
4. The operating system we have used is Window 10 Enterprise (64 bit).
5. We have used the below code for IFC to Wexbim conversion.
protected void ConvertIFCtoWEXBIM(string filePath)
        {
            var IfcTestFile = filePath;
            //using (var model = IfcStore.Open(Server.MapPath(@"SampleHouse.ifc")))
            using (var model = IfcStore.Open(IfcTestFile))
            {
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                var wexBimFilename = Path.ChangeExtension(IfcTestFile, "wexbim");
                using (var wexBiMfile = File.Create(wexBimFilename))
                {
                    using (var wexBimBinaryWriter = new BinaryWriter(wexBiMfile))
                    {
                        model.SaveAsWexBim(wexBimBinaryWriter);
                        wexBimBinaryWriter.Close();
                    }
                    wexBiMfile.Close();
                }
            }
        }

We need to resolve this issue urgently and we have an urgent requirement for this.
Kindly help us to resolve this issue asap. Below is the screen shot for your reference.
![image](https://user-images.githubusercontent.com/49026188/65021228-4df2a400-d94c-11e9-88f8-99a1eabb31b1.png)

Thank you in advance.

**Comment by martin1cerny** [comment] 2019-09-17 08:17
Is your application 32bit or 64bit?

**Comment by Nandhakumar2187** [comment] 2019-09-17 08:54
It is 64 bit.
We have set the Application pool in IIS like below:
![image](https://user-images.githubusercontent.com/49026188/65026780-db3af600-d956-11e9-9872-545e13cc0f12.png)

**Comment by martin1cerny** [comment] 2019-09-17 09:25
If there is Xbim.Geometry.Engine32.dll in your bin folder, try to remove it. Web server might be trying to load both automatically which would be causing a clash.

**Comment by Nandhakumar2187** [comment] 2019-09-17 09:31
Yes, we have already deleted the Xbim.Geometry.Engine32.dll and still we have received the same error.

**Comment by Nandhakumar2187** [comment] 2019-09-17 09:38
We have used the "XbimWebUI-master" github project for IFC to Wexbim conversions. It will works if it is a 32 bit application.

But if we make our application as 64 bit -  we have added the Xbim.Geometry.Engine64.dll and we are getting the below error.
![image](https://user-images.githubusercontent.com/49026188/65030336-fad51d00-d95c-11e9-8f63-27ae9c913908.png)

**Comment by martin1cerny** [comment] 2019-09-17 09:56
This issue is a duplicate of #215 and other issues already solved. Please, search closed issues for this.

**Closed** 2019-09-17 09:57 UTC

**Comment by Nandhakumar2187** [comment] 2019-09-17 10:18
We have checked that also, still facing the same issue.

**Comment by andyward** [comment] 2019-09-17 10:38
You're using an old v4 version of Xbim.Engine.Geometry.Interop.dll with a new v5.x version of Xbim.Geometry.Engine64.dll

They're not compatible. The `Logger` property mentioned in the error message was removed in this commit 2 years ago:

https://github.com/xBimTeam/XbimGeometry/commit/ec3ebdfb83fc1d35ce03cfad2c6195e97e808553#diff-4695f2d1a01e6e9033b78708dfdfec8d 

Make sure you're using the latest nuget packages for everything. Don't add assembly references - use Nuget.

**Comment by Nandhakumar2187** [comment] 2019-09-17 10:42
Ok..thanks...

Could you please let us know the latest version of neget?

It will be useful to get those DLLs from latest nuget.

**Comment by martin1cerny** [comment] 2019-09-17 11:07
https://www.nuget.org/packages/Xbim.Geometry/

**Comment by Nandhakumar2187** [comment] 2019-09-17 11:15
Yes , As you mentioned above - we have used the latest version of DLLs. Please refer below screen shot.
![image](https://user-images.githubusercontent.com/49026188/65037022-712c4c00-d96a-11e9-855d-913214f2401f.png)

The latest version also we are facing the issue.

**Comment by andyward** [comment] 2019-09-17 11:17
What's in your csproj references? In particular where is it referencing Xbim.Geometry.Engine.Interop from?

Random thought: have you picked up an old reference from the GAC?

**Comment by Nandhakumar2187** [comment] 2019-09-17 11:24
The below is the csproj reference screen shot.
![image](https://user-images.githubusercontent.com/49026188/65037563-9bcad480-d96b-11e9-97b1-6609c2010c68.png)
we have downloaded all DLLs from nuget package manager. We have not picked up from old reference.

**Comment by Nandhakumar2187** [comment] 2019-09-17 11:26
We have done the sample project by using the latest version of DLLs.
shall we upload the full sample source for your check?

**Comment by andyward** [comment] 2019-09-17 11:32
That's the wrong part of the CSProj. You're looking for a line like this:

```
<Reference Include="Xbim.Geometry.Engine.Interop, Version=5.1.0.0, Culture=neutral, PublicKeyToken=11e3655e576ec5a9, processorArchitecture=MSIL">
      <HintPath>..\packages\Xbim.Geometry.Engine.Interop.5.1.268-develop\lib\net47\Xbim.Geometry.Engine.Interop.dll</HintPath>
</Reference>
```

If you don't have a hint path then look at where VS has actually picked it up from (select the assembly in the project and look in the properties Window)

**Comment by Nandhakumar2187** [comment] 2019-09-17 11:35
Please find this one.
![image](https://user-images.githubusercontent.com/49026188/65038338-60310a00-d96d-11e9-90a0-084e5913f262.png)

**Comment by andyward** [comment] 2019-09-17 12:33
You shouldn't be referencing Xbim.Geometry.Engine64 directly. It's loaded dynamically by the interop. Try removing it. How did it get in there?

What are the File Versions on the XBIM dlls in your bin dir? I'm certain you've got a mis-match somehow (And I mean **FileVersion**  _not_ **AssemblyVersion**)

**Comment by Nandhakumar2187** [comment] 2019-09-17 13:28
We have removed the Xbim.Geometry.Engine64.dll from reference and also in bin folder.
Now we have received the different error.
![image](https://user-images.githubusercontent.com/49026188/65045839-2667ff80-d97d-11e9-9d6c-f1436a2e5324.png)

**Comment by andyward** [comment] 2019-09-17 13:37
What are the File Versions on the XBIM dlls in your bin dir? I'm certain you've got a mis-match somehow (And I mean FileVersion not AssemblyVersion)

**Comment by Nandhakumar2187** [comment] 2019-09-17 13:39
We have used the below xbim DLLs.
1. Xbim.Common.dll (File version - 5.1.267.0)
2. Xbim.Geometry.Engine.Interop.dll (File version - 5.1.254.0)
3. Xbim.Ifc.dll (File version - 5.1.267.0)
4. Xbim.Ifc2x3.dll (File version - 5.1.267.0)
5. Xbim.Ifc4.dll (File version - 5.1.267.0)
6. Xbim.IO.Esent.dll (File version - 5.1.267.0)
7. Xbim.IO.MemoryModel.dll (File version - 5.1.267.0)
8. Xbim.ModelGeometry.Scene.dll (File version - 5.1.254.0)
9. Xbim.Tessellator.dll (File version - 5.1.267.0)

**Comment by andyward** [comment] 2019-09-17 16:33
So now it looks like you don't have any xbim.Geometry.EngineXX.dll deploying. Is that right? That would explain the error above.

Can you clean the bin, delete your packages folder and do a Nuget restore. (to force a re-fetch of the Xbim packages)

If that still has issues, can you try updating Geometry to the latest Myget version from develop. You should see Xbim.Geometry.Engine `5.1.268-develop` in xbim_develop if you add https://www.myget.org/F/xbim-develop/api/v3/index.json as a nuget source

**Comment by andyward** [comment] 2019-09-17 16:34
This doesn't explain where you're getting that v4 version of Xbim.Geometry.Engine.Interop.dll from...

**Comment by Nandhakumar2187** [comment] 2019-09-18 07:19
yes, we do not have any xbim.Geometry.EngineXX.dll in bin folder now. and we have also not referenced the xbim.Geometry.EngineXX.dll in References.
But in packages folder we have the xbim.Geometry.EngineXX.dlls in the below folder
D:\Sample Projects\BIMTest64\packages\Xbim.Geometry.Engine.Interop.5.1.254\build\net47

**Comment by Nandhakumar2187** [comment] 2019-09-18 09:08
Could you please let us know how to install Myget into my project?

**Comment by Nandhakumar2187** [comment] 2019-09-18 09:17
We have clean the bin folder and we have deleted the package folder and we have done the Nuget restore. Still we have the issues.

Please let us know, is it possible to get the Xbim.Geometry.Engine 5.1.268-develop from Nuget?

If not possible, please let us know how to  install Myget into my project.

**Comment by andyward** [comment] 2019-09-18 10:21
Add this file to the root of your solution: https://github.com/xBimTeam/XbimGeometry/blob/master/nuget.config

In the Nuget window you should see `xbim_develop` as a source as well as Nuget (you may need to restart VS after adding the file for it to get picked up)

**Comment by Nandhakumar2187** [comment] 2019-09-18 11:31
We have added nuget.config in root folder.
![image](https://user-images.githubusercontent.com/49026188/65144812-bc5f6100-da35-11e9-9c4b-dcc807f82935.png)
Then we have closed the Visual Studio and reopen it again.
We could not see the xbim_develop in source.
![image](https://user-images.githubusercontent.com/49026188/65144891-e9137880-da35-11e9-91f4-096aa11cc978.png)

**Comment by andyward** [comment] 2019-09-18 11:55
https://stackoverflow.com/questions/42736107/where-is-nuget-config-file-located-in-visual-studio-2017-project

**Comment by Nandhakumar2187** [comment] 2019-09-18 12:03
When it will be released to Nuget?

**Comment by andyward** [comment] 2019-09-18 14:44
Maybe a week or 2. Did Myget work for you?

**Comment by Nandhakumar2187** [comment] 2019-09-18 14:48
No.currently we are checking. we will let you know if we face any issues.

**Comment by Nandhakumar2187** [comment] 2019-09-20 09:33
Hi,
Now the 'Xbim_devlop' has been listed in the Nuget source drop down.
![image](https://user-images.githubusercontent.com/49026188/65316272-41be4f00-dbb7-11e9-9c48-f44841ceaff7.png)

We have downloaded all the xbim related dll files from the 'Xbim_devlop' source. Still we are facing the below issue.
![image](https://user-images.githubusercontent.com/49026188/65316513-be512d80-dbb7-11e9-832d-6f432e9e33b7.png)

**Comment by Nandhakumar2187** [comment] 2019-09-20 09:34
Also we cannot see any DLLs in the name of "Xbim.Geometry.Engine.dll".

**Comment by andyward** [comment] 2019-09-20 10:44
There isn't a Xbim.Geometry.Engine.dll. Because we need to switch between 32 & 64 bit dynamically we're [intercepting the assembly resolve](https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.Geometry.Engine.Interop/XbimCustomAssemblyResolver.cs) and probing for the right DLL. 

The important question is do you see a copy of Xbim.Geometry.Engine[32/64].dll in the bin folder. If you don't that's the problem you need to resolve.

**Comment by Nandhakumar2187** [comment] 2019-09-20 10:52
We do not see the Xbim.Geometry.Engine[32/64].dll in bin folder.
But we have seen the Xbim.Geometry.Engine[32/64].dlls in the below packages path.
D:\Sample Projects\WebApplication2\packages\Xbim.Geometry.Engine.Interop.5.1.273-develop\build\net47

Do we need to copy the both DLLs into bin folder?

**Comment by Nandhakumar2187** [comment] 2019-09-20 11:01
if we do copy the the Xbim.Geometry.Engine[32/64].dll in bin folder, this also having same error.

We do not know what we can do to resolve this issue.

**Comment by andyward** [comment] 2019-09-20 11:35
I think you should share your WebApplication2 solution in github so we can help. Without code and a repro this is going nowhere...

**Comment by Nandhakumar2187** [comment] 2019-09-20 11:56
we are not able to upload the whole project in gitup. We have tried this and it show below error.
**Yowza, that’s a big file. Try again with a file smaller than 25MB.**

I have compressed the source in zip folder, the size is 91 MB.

Please provide the path to upload the source.

**Comment by andyward** [comment] 2019-09-20 12:02
Can't you just push the code to a github repo? I don't want a zip file - it's 2019

For info you don't need to copy the _packages_ folder or any _bin_ or _obj_ folders. That's why it's so big.

**Comment by Nandhakumar2187** [comment] 2019-09-20 12:29
we have uploaded the files in the below repository
https://github.com/Nandhakumar2187/IFCtoWexbim

**Comment by andyward** [comment] 2019-09-20 12:47
Half the code is missing from this repository - so it won't compile. 

Sorry, I'm done with this investigation - I can't waste any more time.

**Comment by Nandhakumar2187** [comment] 2019-09-20 12:57
Sorry for the inconvenience caused. We have uploaded whatever the files we have in WebApplication2 except packages , bin and object folder.
Please help us on this.

**Comment by andyward** [comment] 2019-09-20 13:54
Sorry I'm **not** prepared to unpack multiple zip files to get a simple build to work. I just wanted to clone the repo and build it.

I'm going to be blunt. My diagnosis on this issue is you need to first understand some basics of .NET / web software development, like  [source code management
](https://github.com/firstcontributions/first-contributions/blob/master/github-windows-vs2017-tutorial.md ) and [package management](https://docs.microsoft.com/en-us/nuget/what-is-nuget) .  

Building web-based BIM solutions is hard - but it's even harder without a good foundation. If you're spending days on simple stuff like this you're going to struggle when you hit a real issue.

**Comment by Nandhakumar2187** [comment] 2019-09-20 14:14
Ok. Thank you for the feedback.

**Comment by sktzoootech** [comment] 2019-10-30 21:55
I created a new asp.net 4.7 project on VS2017 and added xbim essentials and xbim geometry.  I am having the same issue as Nandhakumar.

I've tried using the develop versions of the packages but the same thing happens.

You can check out the following to recreate the issue: https://github.com/sktzoootech/ifcgeotest.git

@andyward - appreciate spending your time on this issue but I hope the above project on git will at least give you an idea whats going on.  I hope you can spare a little bit more time on this issue.  Thank you so much and I appreciate your help.

**Comment by kingsjakal** [comment] 2020-06-13 08:55
I have created a Asp.net Application and I am getting the same error as mentioned.

@andyward

**Comment by andyward** [comment] 2020-06-14 14:49
If you're seeing 'Bad Image format' exceptions under ASP.NET it usually means you're targeting _AnyCPU_ platform (which copies both x86 and x64 Geometry engines to the bin folder). Create & target a Platform configuration for x86 or x64 in your solution and it will only copy the correct Geometry DLL.

@sktzoootech Sorry I missed this post back in Oct 19 as this issue was closed. Try updating to the latest geometry engine from nuget.

**Comment by rainer-helbing** [comment] 2021-11-13 10:09
I was getting a 'Bad Image format' exception even with the correct geometry engine DLL on my test machine, because I forgot to install the VC++ runtime.

**Comment by rubit0** [comment] 2022-12-13 23:20
I'm experiencing the same problem when deploying to an azure app service but moving the *.dll file manually via FTP to the deployed folder fixed the issue.

Kinda strange how the needed files are emitted into the bin folder but when deploying via the azure tooling, the Xbim.Geometry.Engine32/64.dll files are ignored.

**Comment by Rachvel** [comment] 2024-08-27 13:58
This workaround [#312](https://github.com/xBimTeam/XbimGeometry/issues/312#issuecomment-2312640981) can be interesting for someone.
