### ISSUE TITLE
weird meshes

### ISSUE THREAD

**Issue by dontbmh** [xBimTeam/XbimGeometry#47] opened 2017-04-01 06:34 UTC
I use XbimGeometry and FBXSDK to export  fbx from ifc. However, I got some weird meshes in the model. This also happened when view this ifc in XbimXplorer. The description image and ifc file are attached here. Any suggestions? Thanks in advance.

![test](https://cloud.githubusercontent.com/assets/1356599/24576097/09a62764-16e8-11e7-95f4-f5efc98031b7.png)
[CJ_1.zip](https://github.com/xBimTeam/XbimGeometry/files/887416/CJ_1.zip)

**Comment by CBenghi** [comment] 2017-04-02 08:29
Hello, 
I can have a look at this, can you tell me what version is it that you are using?
Also, this is very interesting, would you be happy to share the code with the community, or is it part of some proprietary solution?
Claudio

**Comment by CBenghi** [comment] 2017-04-04 10:58
I've added a file in the XbimGeometry\Xbim.Geometry.Engine.Tests\ToInvestigate folder of the solution.
The problem is happening because of dirty mesh structures in the IfcPolyLoops exported by Tekla.
We'll look into them to see if there's a safe way to fix this preventing other regressions.

I'm attaching the fixed model, that looks like this:

![image](https://cloud.githubusercontent.com/assets/5476273/24653467/da34f79c-192d-11e7-95dc-fc42d67b0fa6.png)

[CJ_1.zip](https://github.com/xBimTeam/XbimGeometry/files/892846/CJ_1.zip)

**Comment by dontbmh** [comment] 2017-04-05 02:45
CBenghi,

I appreciated your response. We always fixed the weird meshes in TEKLA after found them in FBX. If xBim can figure this out through pre-processing or some kind, that would be fantastic.

BTW, for the FBX exporter, we are currently still investigating, testing, and it's not stable sometimes.
Our goal is to at least support exporting geometry and property information from TEKLA, CATIA and REVIT.
After it's being functionally tested and well-documented,  we are happy to share this with community.

**Comment by CBenghi** [comment] 2017-04-05 14:40
Ok then, 
the code that does this fix is in the latest develop branch of XbimXplorer...
it's highly experimental though, play with it carefully.

XbimXplorer.Commands.Fixer.Fix(IfcStore store)

once issued the command (through the command interface) you can save the file as a new name and the model should improve.

Steps to use:
1) open the file in xplorer 
2) ensure in the development mode in the settings is set.
3) open View/Developer Windows/Commands from the menu
4) type the command "modelfix" in the upper part of the window, then press run button.

Best,
Claudio

I'll close the issue, as I've handed over the files in the investigation folder for further fixes, but we don't know whether we'll do something about this in geometry as there are serious regression risks in doing so. 
But reopen it if you think it's worth it.

**Closed by CBenghi** 2017-04-05 14:40 UTC
Labels: enhancement

**Comment by dontbmh** [comment] 2017-04-06 01:15
CBenghi, 

thanks, I'll play around later.

**Comment by foaq** [comment] 2017-08-25 06:51
Hello dontbmh,

can you please share the code with us? Would be really great.
Thank you in advance.
