### ISSUE TITLE
Missing some walls in loaded SampleHouse4.ifc

### ISSUE THREAD

**Issue by alexmatv70** [xBimTeam/XbimGeometry#249] opened 2020-02-24 11:14 UTC
*Model loaded by xBIM 5.1.x is incomplete. There was no such problem on previous version of xBIM (5.0 and 4.x). The issue is detected on provided SampleHouse4.ifc*

#### Assemblies and versions affected:

*__XbimWindowsUI release 9 Oct 2019__ SHA:13bb09ab7543d23a6fee1892e60c250c374150d3
* __Xbim.Essentials 5.1.274__ 
* __Xbim.Geometry.5.1.283__

#### Steps (or code) to reproduce the issue:

1) Checkout __XbimWindowsUI
2) Build (Debug or Release)
3) Run
4) Open SampleHouse4.Ifc

#### Minimal file to reproduce the issue:
*https://github.com/xBimTeam/XbimEssentials/blob/master/Tests/TestFiles/SampleHouse4.ifc*

#### Expected behavior:

*No missing walls* Screenshot from XbimXplorer 4.0.14-V007:
https://gyazo.com/69084daa600b67d99b4a54dc466b6a49

#### Actual behavior or exception details:

*There are missing walls* See screenshot: https://gyazo.com/eeccd6e4f9f0cc1e8a6118a1bb4245cc

#### Additional Details

OS: Windows 10 Pro

Worked fine on xBIM 5.0 and previous versions of xBIM: 
* Xbim.Essentials.5.0.213
* Xbim.Geometry.5.0.163

Log: https://gyazo.com/a073b051f5c61f6a957c5182bae10e5e

**Comment by andyward** [comment] 2020-02-24 11:26
Confirmed:

Looks like this may the culprit

`Warning
Xbim.ModelGeometry.Scene.Xbim3DModelContext
GeomEngine: #2315="IfcClosedShell" ["Very small closed IfcClosedShell has been ignored"]`

**Comment by bekraft** [comment] 2020-02-24 13:17
It's a duplicate of https://github.com/xBimTeam/XbimWindowsUI/issues/119. The logic of how geometrically open shells are skipped has been changed in xBimTeam/XbimGeometry@aa7e88f#diff-0709a275ed09d3306fb4a5caf5a04aa7.

**Comment by alexmatv70** [comment] 2020-02-24 14:03
Yes, it looks the same problem. I've created this issue here because it is not in XbimWindowsUI code.
Please fix SampleHouse4.ifc if this bug is because of incorrect data. But I am not sure it will not happen on other IFC files produced by different popular software. It is very usual case when some files have some specifications deviations. I am afraid upgrading to latest xBIM release due to that issue and prefer to stay with 5.0.

**Comment by andyward** [comment] 2020-10-17 16:16
Fixed in Geometry 5.1.346 onwards

**Closed by andyward** 2020-10-17 16:16 UTC
Labels: bug
