### ISSUE TITLE
IfcSpace rendered in wexBim

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimGeometry#98] opened 2018-02-26 08:24 UTC
Hello guys,
When I generate a model in Unity based on wexbim I have one issue but I think it's probably cause I missed something.
All the Ifcspace elements are rendered as object in my scene. Is their a way to disable or ignore them during the mesh generation ? Cause for me it mustn't be rendered.

Btw I don't know if this question must be asked here or in the Essentials part. All the parsing that I do on the wexbim is done with xbim.essentials.

Thanks in advance guys !

**Comment by martin1cerny** [comment] 2018-02-26 08:39
The wexBIM data contains product type. So, you can put a hook in your binary parser to ignore anything you don't want.

**Comment by liszto** [comment] 2018-02-26 08:43
oh yeah indeed I will take a look on the product type !
I was a little bit lost cause I reused the binaryreader example from on of your example but there is no documentation on how the wexbim is generated so I didn't know if I missed something during the parsing due to the particular sequence.
The only way to check how it's formatted is to read the c++ part where the geometry is created ?
Even if in your example (I think) your reader already parse everything.

**Comment by martin1cerny** [comment] 2018-02-26 08:52
Yes it does, but it makes certain types of things hidden by default (spaces and openings). The generation code is in `IfcStore` if you want to have a look. Only triangulation data is created in C++ but that is only arrays of vertices, indices and normals which is very straightforward to read and interpret.

**Comment by liszto** [comment] 2018-02-26 09:18
Thanks I found the ifcspace id so I could exclude them during the binaryreader process.
Now I will take a look at the ifcstore saveaswexbim method just to figure out all of this i generated (that could help me a lot for other things I think.)

I will ask you a last question in this ticket (I know it's not related to the first one but I don't know if it's reliable to create a new ticket in xbim.essentials just for this one.

Does the documentation on xbim docs up to date ? cause it seems to be outdated ?
And I want to know if you need help to update it a bit cause sometimes when I read it it's quite complicated to find what I want when it's not just missing due to the current library state ^^

**Comment by martin1cerny** [comment] 2018-02-26 09:26
I have to admit we don't pay great attention to the documentation so it is likely to be outdated. All information at http://docs.xbim.net/ should be up to date but documentation generated from code is not. Part of the problem is that absolute most of the code is "just" an implementation of IFC2x3 and IFC4 and I can't see the point in duplication of the official schemas documentation.

**Comment by liszto** [comment] 2018-02-26 11:03
@martin1cerny if some of you are interested. I succeeded by recreated a doc up-to-date based on the current master branch from xbim.essentials.
I take a look at this project "https://github.com/xBimTeam/XbimDocs" and I generate the documentation with the sandcastle plugin that he used.

**Comment by martin1cerny** [comment] 2018-02-26 13:28
You are welcome to submit a PR to XbimDocs master branch and to `gh-pages` which contains content publicly available at http://docs.xbim.net/XbimDocs.

**Comment by martin1cerny** [comment] 2018-02-27 12:40
Closing and saying big THANK YOU to @liszto again for updated code documentation at http://docs.xbim.net/XbimDocs

**Closed by martin1cerny** 2018-02-27 12:40 UTC
