### ISSUE TITLE
Uncorrect solid boolean operation

### ISSUE THREAD

**Issue by svblu** [xBimTeam/XbimGeometry#113] opened 2018-06-07 09:18 UTC
#### Expected behavior:
Hello,
I'm tryng to open a IFC file with XBim.

The result that I expect is:
![imgstair](https://user-images.githubusercontent.com/40022025/41088290-6f42cd38-6a3f-11e8-839f-288a3d89bbac.jpg)
 
but when I open this IFC file the result is:
![imgstair2](https://user-images.githubusercontent.com/40022025/41089615-8e15df40-6a42-11e8-9785-a674a381ca60.jpg)

In XbimXplorer I have the same issue with a compiled version of the solution on my machine:
![imgstair3](https://user-images.githubusercontent.com/40022025/41091472-e8566ba6-6a46-11e8-991a-ef364dc73078.jpg)

But if I use a compiled version from installable distribution the file is read correctly:
![imgstair4](https://user-images.githubusercontent.com/40022025/41091256-6b84ee54-6a46-11e8-93a3-c4e1714d6084.jpg)

To read the geometry shapes in the file i use this code:

#### Minimal code (or steps) to reproduce the issue:
```cs
public static void TransformFromProduct(IIfcProduct product, IfcStore model)
   var shape = ctx.ShapeInstancesOf(product);
   var productShape = shape.Where(s => s.RepresentationType != XbimGeometryRepresentationType.OpeningsAndAdditionsExcluded).ToList();
   foreach (XbimShapeInstance shapeInstance in productShape)
   {
       XbimShapeGeometry geometry = ctx.ShapeGeometry(shapeInstance.ShapeGeometryLabel);
       MemoryStream ms = new MemoryStream(((IXbimShapeGeometryData)geometry).ShapeData);
       BinaryReader br = new BinaryReader(ms);
       XbimShapeTriangulation mesh = br.ReadShapeTriangulation();
       mesh = mesh.Transform(shapeInstance.Transformation);
       ...
    }
}
```
It seems that the solid boolean operation works in inverse way, but it's only a empiric observation.

#### Versions of xBIM Packages:

- xBIM Essentials: 4.0.29
- xBIM Geometry: 4.0.11 

#### Minimal file to reproduce the issue:
[scala_travi.zip](https://github.com/xBimTeam/XbimGeometry/files/2079742/scala_travi.zip)

**Comment by CBenghi** [comment] 2018-06-11 14:47
Duplicate of closed issue https://github.com/xBimTeam/XbimWindowsUI/issues/83

**Closed by CBenghi** 2018-06-11 14:47 UTC
