### ISSUE TITLE
Unable to set control points to IfcBSplineSurface

### ISSUE THREAD

**Issue by anil1610** [xBimTeam/XbimGeometry#235] opened 2019-12-19 07:21 UTC
Unable to set control points to IfcBSplineSurface

I am using below code to set control points of IfcBSplineSurface. 
I tried other possible ways that I can think of. But ifcBSplineSurface.ControlPoints.count is always showing zero.

This is working properly for a local instantiated List<List<XbimPoint3D>>. but not to ifcBSplineSurface.ControlPoints.count. 

Let me know if am missing something. 

// fill control points
                for (int iU = 0; iU < iNoOfPtsInU; iU++)
                {
                    List<XbimPoint3D> VPoints = new List<XbimPoint3D>();

                    for (int iV = 0; iV < iNoOfPtsInV; iV++)
                    {
                     
                        XbimPoint3D Pt = new XbimPoint3D(ControlPts[iU][iV].X, ControlPts[iU][iV].Y, ControlPts[iU][iV].Z);
VPoints.Add(Pt);

                    }
                    ifcBSplineSurface.ControlPoints.Add(VPoints);
                }

**Comment by andyward** [comment] 2019-12-19 14:50
Duplicate of https://github.com/xBimTeam/XbimEssentials/issues/304

**Closed by andyward** 2019-12-19 14:50 UTC
