### ISSUE TITLE
ShapeUpgrade_UnifySameDomain causes a freeze

### ISSUE THREAD

**Issue by santiagoIT** [xBimTeam/XbimGeometry#483] opened 2024-06-05 21:43 UTC
Opening the attached IFC is not possible using the self-compiled XBim-Explorer (developer) branch.

During opening the program hangs and after a long wait the process dies.

What is causing the issue is a particular IfcBeam (#60042):
![image](https://github.com/xBimTeam/XbimGeometry/assets/1231891/cc1b416a-fcf7-481a-a8ef-cf159215d03f)

The problem happens when the ShapeUpgrade_UnifySameDomain is executed:
![image1](https://github.com/xBimTeam/XbimGeometry/assets/1231891/c2ac496c-d45a-4d2e-8c98-8f62c3b0150f)

if that line is commented out, the file opens fine.

This is the precise line where the program seems to hang forever:

![image](https://github.com/xBimTeam/XbimGeometry/assets/1231891/8ece4918-47df-4b97-b525-db946854b7ff)

In this case the solid is the result of calculated CSG solids. Is it really necessary to unify faces, edges after a boolean operation?
I have zero experience with Open-Cascade, but from experience with other modelers it seems odd to me.

I would expect to do something like that if a BREP is read in from an IFC file. In that case it makes sense to unify faces/edges.

Would be great to have some feedback. Ideally it is not always necessary to perform the face/edge cleanup.

A side remark:

The last oficial release of the XbimViewer (v4 I believe) opens the file just fine.

This is how the beam looks like (using a different IFC Viewer):

![image](https://github.com/xBimTeam/XbimGeometry/assets/1231891/42abf6b5-78f1-4be3-8fd2-168637abe2f6)

Let me know if I should try to look deeper into the problem. Maybe I am able figure something out, or if I hope it is not always necessary to do the face/edge cleanup. That is also something I could implement if you help me understand when not to execute it.

[testFile.zip](https://github.com/user-attachments/files/15596722/testFile.zip)

**Comment by andyward** [comment] 2024-06-06 09:09
Perhaps @Ibrahim5aad can shed some light?

**Comment by Ibrahim5aad** [comment] 2024-06-30 12:40
Hi @santiagoIT, sorry I wasn't able to pick this earlier. Sadly, this is a long-standing issue for the **ShapeUpgrade_UnifySameDomain** algorithm, for some particular topologies and under some fuzzy tolerances in the Boolean operation, the output shape can cause the the unifier to hang and get stuck in some infinite loop. We provided some problematic shape before to a tracking ticket on OCC tracker, but it is still an open issue: https://tracker.dev.opencascade.org/view.php?id=32949


One thing you can do is to tweak the fuzzy tolerance of the Boolean operation a little bit . You don't need to dig into the codebase for that. The V5 engine have some application setting called **FuzzyFactor** that you can use. It is a factor that the model tolerance is multiplied with and used the the fuzzy tolerance of the Boolean operation. 

![image](https://github.com/xBimTeam/XbimGeometry/assets/50090593/c18d5b5c-567d-451d-889b-3267cd780047)

The default value is 10.

![image](https://github.com/xBimTeam/XbimGeometry/assets/50090593/9b1744b3-d093-427d-8308-044a0905487c)

I tried to set it to 1 and I got the IfcBeam (#60042) processed fine.

**Comment by santiagoIT** [comment] 2024-07-01 16:48
@Ibrahim5aad @andyward 
Thank you for the valuable info. Indeed, by setting the FuzzyFactor to 1 the file opens fine.

Would it make sense to expose the public static values in XbimGeometryCreator to managed code, so that they can be set/modified at runtime?
My suggestion would be to expand: IXbimGeometryCreator with the following properties:

```
static int BooleanTimeOut;
static double FuzzyFactor;
static double LinearDeflectionInMM;
static double AngularDeflectionInRadians;
static bool IgnoreIfcSweptDiskSolidParams;
```

Then managed code could set those values. That would be beneficial for us since we provide a class library.

Let me know your thoughts/suggestions, I could then create a pull request.

**Comment by santiagoIT** [comment] 2024-07-01 16:56
Now that I think about it further, the better approach would be add a static class:
**XbimGeometryCreatorSettings** to Xbim.Geometry.Engine and expose the properties there.

**Comment by andyward** [comment] 2024-07-16 08:49
Hi @santiagoIT 

Agreed I'd avoid extending _IXbimGeometryCreator_ - partly since the implementation may not be singleton and the lifetime of the GE is not always in the user's control. So you'd potentially find your setting being missed out

A static settings class would work - albeit there may be edge-case concurrency issues (but note the GE is not fully re-entrant anyway). 

In the net6 branch I would probably adopt the Options pattern and have an `IOptionsMonitor<GeometrySettings>` passed in the GE constructor. That way you could change the settings dynamically at runtime.

**Comment by santiagoIT** [comment] 2024-11-05 22:10
Hello,

I have run into another case where an infinite loop occurs.

To reproduce set the FuzzyFactor to 1 and open the attached file.
[InfiniteLoop_ShapeUpgrade_UnifySameDomain.zip](https://github.com/user-attachments/files/17638960/InfiniteLoop_ShapeUpgrade_UnifySameDomain.zip)

You can reproduce using the latest XBim-Explorer (developer) branch.

Setting FuzzyFactor >= 2 avoids the infinite loop.

I see there was some activity on the OCC trying to address the issue. But it seems the issue is still open.

**Comment by andyward** [comment] 2024-12-23 17:36
Confirmed fixed in v6. Added test

**Closed by andyward** 2024-12-23 17:36 UTC

**Comment by santiagoIT** [comment] 2024-12-23 17:59
Andy, that is great news!! Thank you!
I ran into that problem several times.

What is the status with v6, any estimate when it will be released?

**Comment by andyward** [comment] 2024-12-23 23:26
Nice timing: There's a preview out now in Nuget. See
https://www.nuget.org/packages/Xbim.Geometry/6.1.801-netcore

This is missing 4-5 fixes from develop/master (but should be synced up in a
week or so) - even so it's worth checking out.

Expect some follow up builds in early 2025, including net8 support.
