### ISSUE TITLE
Repeated elements not visible

### ISSUE THREAD

**Issue by Tpullmann** [xBimTeam/XbimGeometry#92] opened 2018-02-11 12:27 UTC
Hi,

I've got an ifc file which contains a group of elements. Other tools like Tekla BimSight show it "correctly" (at least like in the authoring software Archicad). 
![bimsight](https://user-images.githubusercontent.com/20210196/36073336-36bbfcc0-0f2f-11e8-8647-b0ee8b619585.png)

In XBim (also in the explorer) we see only one element out of the group.
![xbim explorer](https://user-images.githubusercontent.com/20210196/36073338-3be94536-0f2f-11e8-92bf-234482f297cc.png)

[Export_123_IFC_2018_1_5_18_17.zip](https://github.com/xBimTeam/XbimGeometry/files/1714345/Export_123_IFC_2018_1_5_18_17.zip)

Is the IFC file corrupt or do we have a gap?

**Comment by martin1cerny** [comment] 2018-02-12 08:17
I checked and the file doesn't seem to be corrupted. I tried to open in DDS CAD viewer as well and that said there were unrecoverable errors and rendered something completely different to both of your images. So, there is something hapenning in the data. xBIM is often more rigorous than Solibri but it should always report problems in the viewer if there are any. Which is not the case here. I had a look in the file and this element is boolean clipping result which subtracts 4 faceted BReps from an extruded profile. This kind of definition seems to be overcomplicated and error prone.

@CBenghi is more familiar with the actual geometry processing. What do you think Claudio?

```
#90880=IFCBUILDINGELEMENTPROXY('0wwfH1Jef5aOAljJ1xgZR2',#12,'Decke-001',$,$,#90643,#90876,'3AEA9441-4E8A-4591-82AF-B5307BAA36C2',$);
#90643=IFCLOCALPLACEMENT(#115,#90642);
#90642=IFCAXIS2PLACEMENT3D(#90640,#90638,#90636);
#90640=IFCCARTESIANPOINT((38.41,0.7,3.4));
#90638=IFCDIRECTION((0.,0.,1.));
#90636=IFCDIRECTION((1.,0.,0.));
#90876=IFCPRODUCTDEFINITIONSHAPE($,$,(#90868,#90874));
#90868=IFCSHAPEREPRESENTATION(#142,'Body','CSG',(#90867));
#90867=IFCBOOLEANRESULT(.DIFFERENCE.,#90866,#90863);
#90866=IFCBOOLEANRESULT(.DIFFERENCE.,#90865,#90814);
#90865=IFCBOOLEANRESULT(.DIFFERENCE.,#90864,#90765);
#90864=IFCBOOLEANRESULT(.DIFFERENCE.,#90664,#90716);
#90664=IFCEXTRUDEDAREASOLID(#90654,#90661,#90662,0.1);
#90654=IFCARBITRARYCLOSEDPROFILEDEF(.AREA.,'',#90652);
#90652=IFCPOLYLINE((#90644,#90646,#90648,#90650,#90644));
#90644=IFCCARTESIANPOINT((0.,0.));
#90646=IFCCARTESIANPOINT((9.39,0.));
#90648=IFCCARTESIANPOINT((9.39,6.7));
#90650=IFCCARTESIANPOINT((0.,6.7));
...
```

**Comment by martin1cerny** [comment] 2018-02-12 08:27
I checked and the file doesn't seem to be corrupted. I tried to open in DDS CAD viewer as well and that said there were unrecoverable errors and rendered something completely different to both of your images. So, there is something hapenning in the data. xBIM is often more rigorous than Solibri but it should always report problems in the viewer if there are any. Which is not the case here. I had a look in the file and this element is boolean clipping result which subtracts 4 faceted BReps from an extruded profile. This kind of definition seems to be overcomplicated and error prone.

@CBenghi is more familiar with the actual geometry processing. What do you think Claudio?

[Here](https://github.com/xBimTeam/XbimGeometry/files/1715661/Export_123_IFC_2018_1_5_18_17_clean.zip) is the minimal example.

**Comment by bekraft** [comment] 2018-10-18 11:47
I came accross the same roblem for Ifc2x3 models. While taking a deep dive into the geometry package, I saw a weird XbimSolid code fragment, which accepts only the first outcome of a boolean op in `XbimSolid::Init(IIfcBooleanResult^ solid)` (XbimSolid.cpp):
```	    
TopoDS_Solid  shape = (XbimSolid^)(xbimSolidSet->First);
if (!shape.IsNull())
{
	pSolid = new TopoDS_Solid(); //make sure this is deleted if not used
	*pSolid = shape; //just take the first as that is what is intended by IIfc schema
}
```
Means, the method drops all other results. Since a boolean cut can yield multiple unconnected shells (solid in xbim terms), this method won't return the proper result. Am I correct?

**Comment by bekraft** [comment] 2018-10-22 12:01
@martin1cerny @CBenghi Deep dive taken: It's not only this small fragment. There are multiple issues concerning CSG trees. First, I think there's some misalignment between IFC's "solid" and Xbim's "solid". While a "solid" in terms of the IFC is something made of multiple geometrical objects, xbim uses it for "shells" (there's a select "IfcSolidOrShell", http://www.buildingsmart-tech.org/ifc/IFC4/final/html/schema/ifcgeometricconstraintresource/lexical/ifcsolidorshell.htm). 
Indeed, a solidset of xbim maps to the "solid" of the IFC. It's a little more complicated … 

Finally, I've refactored some code of the geometry factory aka `IXbimGeometryEngine` and the underlying OCC adaption (see https://github.com/xBimTeam/XbimGeometry/compare/develop...bekraft:bugfixes/92).  I'll open another PR.

**Comment by andyward** [comment] 2018-11-26 12:37
Confirmed fixed in v5 - througth to Explorer (develop)
![image](https://user-images.githubusercontent.com/923699/49014406-ededff80-f177-11e8-994c-d4ae42bb329b.png)

**Closed by andyward** 2018-11-26 12:37 UTC
Labels: bug

**Comment by SteveLockley** [comment] 2018-11-27 12:39
This is now resolved in Version 5, currently in the develop branch, thanks to BEKraft for his help on this one
