### ISSUE TITLE
Unity3D : Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by koreitfree** [xBimTeam/XbimGeometry#86] opened 2018-01-19 12:25 UTC
Hello
There is now a problem with the xBim DLL on unity3D.
IfcStore.Open Function works normally but I have debugged because of a problem in Context.CreateContext ();
 var oh = Activator.CreateInstance (ass.FullName, "Xbim.Geometry.XbimGeometryCreator"); An error occurs in this part.
The error content is Exception has been thrown by the target of an invocation. is

1. unity3D 
    [base.cs]
        model = IfcStore.Open("D:\\DATA\\IFC\\airbloom_2.ifc", null, null, null, XbimDBAccess.Read);
        //  onemeter = model.ModelFactors.OneMeter;
        if (model.GeometryStore.IsEmpty)
        {
            var context = new Xbim3DModelContext(model);
            context.CreateContext();   <<== error 
        }
     => Cause of error :  Xbim3DModelContext.cs
          public bool CreateContext(ReportProgressDelegate progDelegate = null, bool adjustWcs = true)
          {
                var geomStorageType = XbimGeometryType.PolyhedronBinary;
                if (_contexts == null || Engine == null) return false <<== Engine is null
2. XbimGeometryEngine.cs
     XbimPrerequisitesValidator.Validate();
     var conventions = new XbimArchitectureConventions();  
     string assemblyName = conventions.ModuleName + conventions.Suffix;
      try
       {
             System.Reflection.Assembly ass = System.Reflection.Assembly.Load(assemblyName); <<==normal Pass 
            try
            {
                  var oh = Activator.CreateInstance(ass.FullName, 
                              Xbim.Geometry.XbimGeometryCreator"); <<== error
                   _engine = oh.Unwrap() as IXbimGeometryEngine;
                }
                catch (Exception e)
                {
                   Debug.Log(e.Message);
                }                                                                                                         
      ==> error message  : Exception has been thrown by the target of an invocation.

**Comment by CBenghi** [comment] 2018-01-19 14:43
Hello @koreitfree,
I'm sorry but there is not enough information in your document to reproduce/understand the problem.
Please post more.
Best,
Claudio

**Comment by koreitfree** [comment] 2018-01-23 06:53
I came to know today.
xbim ifcengine is a mixed C ++ Dll
Unity3D only supports single C ++.
I had a hard time.
xBim is unlikely to be available.
It is very unfortunate.

**Comment by mwymwy** [comment] 2018-01-23 09:20
Just a little tip :

most of the time if call to "context.CreateContext()" doesn't work it's because app couldn't find or load native geometryengine's dll (those who are normally found in x86 and x64 folders)

**Comment by CBenghi** [comment] 2018-01-23 10:18
@mwymwy,
you are quite right... this is probably just what was happening here at a second look.
Thanks!

**Comment by koreitfree** [comment] 2018-01-23 11:40
It was a C ++ problem, not a folder problem.
Unity3d supports C ++ as a singleton,
Hybrid type is not supported.
Using mono frames, unity3d uses mono frames
Only single C ++ is supported.
So I am hard today too.

**Comment by CBenghi** [comment] 2018-01-23 12:27
@koreitfree,
Can you point to a document that describes the unity3d limitations?

**Comment by koreitfree** [comment] 2018-01-23 12:38
http://www.mono-project.com/docs/about-mono/languages/cplusplus/

unity3D uses the Mono Framework.
It is described in the mono homepage.

**Comment by mwymwy** [comment] 2018-01-23 13:34
Please tell me if I'm not right, but I believe that if you are able to open
an ifc file, then your application is able to run managed code.
Despite Unity having some restrictions on what you can call from it, your
application is executed in mono's managed vm.

From this consideration I don't get why xbim .Net libraries who are
properly loaded and able to run should not be able to load native geometry
context libraries they are supposed to call.

If not related to bad folder / dependencies configuration, I have another
suggestion which is that geometry context is not able to run because you
miss some dependancies like the proper version of .net / mono framework and
or MSVC++ redistributables.
try running your app with following files in same folder as main exe :

msvcr100.dll ; msvcp100.dll ; msvcr120.dll ; msvcp120.dll ; and maybe
additionnal others depending on which compiler you use to generate your
application.

Take care to take those with same proc architecture as your application
(x64 / x86)

It would be a shame if Unity3D really brings limits to what may be properly
running without it.
Encapsulating a main project inside a new framework should not stop inside
dependencies from running.


2018-01-23 13:38 GMT+01:00 koreitfree <notifications@github.com>:

**Comment by koreitfree** [comment] 2018-01-24 04:39
mwymwy
I've worked in the direction I suggested.
The results were the same.
I'm frustrated ....

**Comment by koreitfree** [comment] 2018-01-24 05:54
CBenghi
As I said before,
You want to use Windows Web Services.
Is it possible to create a Windows Service and serve it with WCF?

https://github.com/xBimTeam/XbimGeometry/issues/56

**Comment by koreitfree** [comment] 2018-02-02 00:02
Give Up

**Comment by martin1cerny** [comment] 2018-02-02 08:04
[Here](https://github.com/xBimTeam/XbimWindowsUI/issues/62) is one example of xBIM & Unity.

**Comment by stefkeB** [comment] 2018-06-07 12:53
FWIW, I'm using XBIM in Unity on a Mac, but only the Essentials package. I never called any of the geometry methods. I can parse an IFC file, but I basically try to interpret the geometry myself. Lots of work unless you only care about FacetedBrep.

**Comment by andyward** [comment] 2018-11-09 11:28
Sounds like a dupe of #93 - lets track there

**Closed by andyward** 2018-11-09 11:28 UTC
Labels: duplicate, question
