### ISSUE TITLE
Large IFC files (500 MB files) not loaded in Internet Explorer

### ISSUE THREAD

**Issue by Nandhakumar2187** [xBimTeam/XbimGeometry#272] opened 2020-08-01 05:18 UTC
Hi,

Hope you are doing good.

In Web application - We are trying to convert 500 MB IFC file to JSON & Wexbim. 

The files are converted but the BIM model is not displayed in xBIM Viewer if we are using in Internet Explorer. 

We have tried other browsers like Chrome, Microsoft Edge - the BIM model has been displayed in xBIM viewer but it will take 40 seconds for loading.

Please clarify the below questions:
1. Please let us know if any size constraints to load the BIM model in Internet explorer.

2. Please let us know, how to avoid delays if we upload more than 500 MB IFC files in xBIM Viewer.

Thank you in advance.

**Comment by andyward** [comment] 2020-08-03 08:39
Duplicate of https://github.com/xBimTeam/XbimWebUI/issues/293

**Closed by andyward** 2020-08-03 08:39 UTC
