### ISSUE TITLE
fedaration model show /hide problem

### ISSUE THREAD

**Issue by yinweib** [xBimTeam/XbimGeometry#341] opened 2021-05-15 14:00 UTC
when model combined ,the intances selected can't be hide using "hide the selected object" xbim windowsUI,anyone knows Why?

**Comment by andyward** [comment] 2021-05-20 16:26
Duplicate of https://github.com/xBimTeam/XbimGeometry/issues/341

**Comment by andyward** [comment] 2021-05-20 16:27
Duplicate of https://github.com/xBimTeam/XbimWindowsUI/issues/169

**Closed by andyward** 2021-05-20 16:26 UTC
