### ISSUE TITLE
Building scene with no walls and slabs

### ISSUE THREAD

**Issue by guenter1holzeder** [xBimTeam/XbimGeometry#163] opened 2019-02-27 15:43 UTC
A picture says more than words…
![image](https://user-images.githubusercontent.com/42930849/53502451-5a95d480-3aae-11e9-88a4-c613eb78ad56.png)
![image](https://user-images.githubusercontent.com/42930849/53502467-66819680-3aae-11e9-84a3-90af3ce855ee.png)
[Scene with no walls.zip](https://github.com/xBimTeam/XbimGeometry/files/2911024/Scene.with.no.walls.zip)

**Comment by martin1cerny** [comment] 2019-02-27 16:25
The problem is that all walls in this model are assigned to the context with `ContextType == "Design"`. But xBIM is only processing 3D data in `ContextType == "Design"` which is where all the rest of the 3D is referenced. With this small hack it worked:

```cs
var modelContext = model.Instances
    .FirstOrDefault<IIfcRepresentationContext>(c =>
        string.Equals(c.ContextType, "Model", StringComparison.OrdinalIgnoreCase));
var bodyRepresentations = model.Instances
    .Where<IIfcRepresentation>(r =>
        string.Equals(r.RepresentationIdentifier, "Body", StringComparison.OrdinalIgnoreCase))
    .ToList();
if (modelContext != null && bodyRepresentations.Any())
    using (var txn = model.BeginTransaction())
    {
        foreach (var representation in bodyRepresentations)
        {
            representation.ContextOfItems = modelContext;
        }
        txn.Commit();
    }
```

![image](https://user-images.githubusercontent.com/773078/53505532-4c4ab700-3ab4-11e9-9345-9657c7282b38.png)

Do you know which tool has created this file? I like its simplicity very much.

Martin

**Comment by guenter1holzeder** [comment] 2019-03-01 07:28
Now it works, many thanks

The sample is an export from an older version of ArchiCAD.

**Comment by guenter1holzeder** [comment] 2019-03-01 07:28
… and is anonymized

**Comment by martin1cerny** [comment] 2019-03-01 07:54
Interesting. I hope newer versions treat contexts in a better way. This seems to be a bug in the exporter.

**Closed by martin1cerny** 2019-03-01 07:54 UTC

**Comment by andyward** [comment] 2019-03-01 10:57
@martin1cerny I suspect it's this test model http://openifcmodel.cs.auckland.ac.nz/Model/Details/110 (or a variant of it)
