### ISSUE TITLE
40mb IFC file converted to 110mb wexbim?

### ISSUE THREAD

**Issue by ravigarg1** [xBimTeam/XbimGeometry#48] opened 2017-04-03 11:49 UTC
Hello,

I was trying to convert an IFC file of around 40mb size to load in the web browser but the resulting file size was 110mb ( .wexbim) and webUI could not load that file. 

Is there anything wrong with the latest geometry solution. For other .IFC files, it is doing conversion like 4MB to 200Kbs. If I open this file in other IFC viewers like Tekla or Trimble, they are able to render it properly....

Thanks
Ravi

**Comment by ravigarg1** [comment] 2017-04-04 13:05
should i share the file?

**Comment by CBenghi** [comment] 2017-04-04 14:07
I suppose the simple question might be: does the geometry look right?
If so it might be that the particular file just expands poorly to wexbim.
If you want to share your file, feel free to zip it and attach to this thread.
I'll have a look.

**Comment by ravigarg1** [comment] 2017-04-06 05:41
[KHPCC - IFC Model.zip](https://github.com/xBimTeam/XbimGeometry/files/901538/KHPCC.-.IFC.Model.zip)
[TCR - IFC Model.zip](https://github.com/xBimTeam/XbimGeometry/files/901539/TCR.-.IFC.Model.zip)

Hello C Benghi
Attached file for your perusal.

**Comment by DrorSegev** [comment] 2017-04-06 06:11
I played with (before creating the context)
model.ModelFactors.Precision = 1;
model.ModelFactors.ProfileDefLevelOfDetail = 0;
model.ModelFactors.DeflectionTolerance = 2;
model.ModelFactors.DeflectionAngle = 3;

and it reduced the size, but I do not know why
Dror

**Comment by ravigarg1** [comment] 2017-04-06 06:39
Hi Dror Segev,

Were you able to see the model in the WebUI?

**Comment by DrorSegev** [comment] 2017-04-06 07:08
Yes

**Comment by CBenghi** [comment] 2017-04-20 16:37
@ravigarg1 ,
I'm having serious problems opening the files you have posted... what version of the xbim are you using to see the model?
I think the latest version of geometry crashes when meshing the geometry of some Rebars, which, btw, I think are the cause of the problem in size as they make massive use of maps.
Please let me know,
Claudio

**Comment by ravigarg1** [comment] 2017-04-21 07:28
xBIM Geometry - Version 4.0.11

But we are not able to view the model as size of wexbim increased to 110mb instead of compressing.

**Comment by CBenghi** [comment] 2017-04-21 16:25
I'm puzzled because when I try to mesh the model with 4.0.11 I get a lot of errors, however I've isolated a test case. In principle however the growing size of the model depends on the use of maps for several components, so it's not a bug, but a limitation of the wexbim format.
I'll close this issue, and look into the format to see if some optimisation can be made.

**Closed by CBenghi** 2017-04-21 16:25 UTC
Labels: question
