### ISSUE TITLE
Something wrong with XbimGeometry

### ISSUE THREAD

**Issue by chenxx08** [xBimTeam/XbimGeometry#46] opened 2017-03-27 12:28 UTC
Look the attached pictures

![20170327202014](https://cloud.githubusercontent.com/assets/4447956/24356149/5f7337d8-132b-11e7-8e8e-331485d01b1c.png)
![20170327202119](https://cloud.githubusercontent.com/assets/4447956/24356150/5f9b7770-132b-11e7-8881-2535c363f1f1.png)

The orgin ifc file is here.
[Ghasem Ariyani-Revit 2014.zip](https://github.com/xBimTeam/XbimGeometry/files/872425/Ghasem.Ariyani-Revit.2014.zip)

**Comment by mwymwy** [comment] 2017-03-27 12:41
faced similar issue few days ago.

take a look at your Ifc data :
* does the opening has proper dimensions ? (ie : you won't have a correct
boolean operation if opening is tighter than wall
* does the opening is correctly linked to the wall by an IfcRelVoidsElement
?

this may solve your issue.



2017-03-27 14:28 GMT+02:00 Chenxx <notifications@github.com>:

**Comment by CBenghi** [comment] 2017-03-30 01:43
I've extracted the problem to create a smaller file to investigate... I'll come back to you once the investigation is completed.
The file is strange because the wall starts with voids in the brep already, but they disappear when subtractions are computed.

The files have been added to the repository on commit hash 57eb707e03f566b2d391f0dc9fac16097eeba1d5

**Comment by CBenghi** [comment] 2017-05-24 11:47
It looks like there's a fix for this in the upcoming version of opencascade.
We'll review once it's merged in our code.

**Comment by mwymwy** [comment] 2018-04-12 15:59
interested in an update ... Right now we reproduce same issue when trying to use openings to punch holes in brep walls

**Comment by martin1cerny** [comment] 2018-04-13 06:31
Boolean operations on BReps are generally tricky. Especially if the geometry of the opening just touches BRep geometry. Minor imprecision in the alignment might cause the subtraction to fail. Windows are often modelled as a mapped representation which might also degrade the precision when rotation is involved. The effect is even worst if the model uses absolute world coordinates (sometimes in millimetres) because floating point precision than comes in play and decreases numerical precision of the result.

If you are in control of the opening creation, it would be safer to make it bigger on both sides of the wall. That will overcome the issue with precision of alignment. Also, make sure you don't use absolute coordinates in the model but subtract it to the level of IfcSite.

**Comment by AlainBolduc** [comment] 2018-07-11 12:14
Any update on this? it's been a year and the bug is still present using the latest code in develop environment.

Thanks!

**Comment by SteveLockley** [comment] 2018-11-24 10:17
Many thanks for posting this, it has help us track down a long standing bug in the conversion of faceted Breps. There is a test case SubtractionResultsInClosedWindow that checks the fix works.
The issue was two fold, the wall geometry already had the openings cut out, this sometimes happens with revit and it leads to boolean operation fails sometimes due to incorrect tolerances.
In addition though one opening in each of the two large faces of the wall were being skipped in Xbim code due to the ordering of bounds in the ifc file, Hence you could not see the window as the outer leaves of the wall were masking it.
This is now fixed in the develop branch, which we will be publishing shortly as Version 5 of Xbim.
Thanks for your patience,

**Closed by SteveLockley** 2018-11-24 10:17 UTC
Labels: bug
