### ISSUE TITLE
Bug: Reading File; CreateContext() crashes

### ISSUE THREAD

**Issue by martin-loucka** [xBimTeam/XbimGeometry#120] opened 2018-07-12 07:24 UTC
Hello

xBim is an excellent tool. But after a couple months, I run into a problem.
I can not open one Solibri Optimizer processed IFC file.

Do guys know how to deal with it?

**Problem:**
              IfcStore model = IfcStore.Open(ifcFileName);
                if (model.GeometryStore.IsEmpty)
                {
                    var context = new Xbim3DModelContext(model);
                    context.CreateContext(); **// Crashes here**
                }

**StackTrace:**
   at BRepOffsetAPI_MakePipe.{ctor}(BRepOffsetAPI_MakePipe* , TopoDS_Wire* , TopoDS_Shape* )
   at Xbim.Geometry.XbimGeometryCreator.CreateGrid(IIfcGrid grid)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteShapeGeometries(XbimCreateContextHelper contextHelper, ReportProgressDelegate progDelegate, IGeometryStoreInitialiser geometryStore, XbimGeometryType geomStorageType) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 1136
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs) in c:\BuildAgent\work\860c3b913b6c647f\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 678
   at UnitTests.GeoReader.ReadGeo(String ifcFileName) in C:\...\01_Code\99_Tests\_UnitTests\xbimm.cs:line 33

#### Versions of xBIM Packages:
- Xbim.Common v4.0.30319
- Xbim.Geometry v4.0.30319

#### Minimal file to reproduce the issue:
Files content is not public but could be sent per private message.

**Comment by CBenghi** [comment] 2018-07-12 09:06
Hi Martin, 
can you send file references (wetransfer?) to my gmail?
claudio.benghi@gmail.com
I'm doing some code work these days.
Claudio

**Comment by CBenghi** [comment] 2018-07-13 09:36
I've opened the file with the latest version of xplorer and while there are a few warnings and two errors I do not get the crash, so I'm suspecting you are not working on the develop branch.
We should certainly produce an updated master soon, but we're not quite there yet.
Can you check if you can open the file in xplorer?

**Comment by martin-loucka** [comment] 2018-07-13 09:53
Yes. I was able to open it in xplorer... 
Okay, I will give a try with the develop branch.

PS. I am facing another issue with  IIfcElementQuantities. Could you please give me a quick hint how to read all the quantities from the IFC? 

I can get custom Psets easily but not the Quantities :/
Thanks

**Comment by martin1cerny** [comment] 2018-07-13 09:57
Please, see the documentation for [IfcPropertySetDefinition](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcpropertysetdefinition.htm).

**Comment by martin-loucka** [comment] 2018-07-13 10:16
@martin1cerny  Sure, I got to this point. 

But the object  IIfcPhysicalSimpleQuantity does not expose a method to get the value of a property set attribute.  

I can get the name of attribute, type of the attribute (IfcQuantityLength, IfcQuantityArea ...) but not the value.

**Comment by martin-loucka** [comment] 2018-07-13 10:47
@martin1cerny My fault.. It works

**Comment by martin-loucka** [comment] 2018-07-16 13:01
Those two issues are related 
https://github.com/xBimTeam/XbimWindowsUI/issues/88

**Comment by andyward** [comment] 2018-11-09 10:34
Duplicate of #135 - Tracking that one instead

**Closed by andyward** 2018-11-09 10:34 UTC
